name: tiled

# conda env create --force -n tiled -f environment.yml --solver=libmamba
# conda activate tiled

channels:
  - conda-forge
  - defaults

dependencies:

  - python <=3.12

  # additional dependencies of the file directory support additions
  - punx
  - pysumreg
  - spec2nexus

  # rely on pip to install tiled and its dependencies
  - pip
  - pip:  # _use_ pip to install these packages
    - databroker >=2.0.0b52
    - tiled[all] >=0.1.0b11
    - area-detector-handlers
    - event-model >=1.22.1
    - suitcase-mongo
    - suitcase-msgpack
    - h5py
    - hdf5plugin
    - pymongo
    - hdf5plugin
    - pillow
    - netCDF4
    - exdir
